name = "SimplexQuad"
uuid = "f5de1e94-2f77-472d-8c3b-9d09f580ee5e"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
